version: "3.8"

services:
  # bot:
  #   build: ./bot
  #   depends_on:
  #     db-api:
  #       condition: service_started
  #     db:
  #       condition: service_healthy
  #       restart: true

  # db-api:
  #   build: ./db-api
  #   environment:
  #     PORT: 8080
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #       restart: true

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
