version: "3.8"

services:
  bot:
    build: ./bot

  db-api:
    build: ./db-api
    environment:
      PORT: 8080
    ports:
      - 8080:8080

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - polaroids:/data/db
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql

volumes:
  polaroids:
